@baseUrl = http://localhost:8082
@token = COLE_O_ACCESS_TOKEN_AQUI

### Swagger
GET {{baseUrl}}/v3/api-docs

### Cadastro público de usuário
POST {{baseUrl}}/api/usuarios
Content-Type: application/json

{
  "nome": "Mariana Costa",
  "email": "mariana@example.com",
  "senha": "Senha@123"
}

### Login público
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "mariana@example.com",
  "senha": "Senha@123"
}

### Catálogo público
GET {{baseUrl}}/api/produtos

### Criar carrinho protegido
POST {{baseUrl}}/api/carrinhos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "usuarioId": 1,
  "produtoId": 1,
  "quantidade": 2
}

### Criar confirmação de pagamento protegida
POST {{baseUrl}}/api/pagamentos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "carrinhoId": 1,
  "usuarioId": 1,
  "idPagamento": "PAY-2026-000123"
}

### Aprovar pagamento protegido
PATCH {{baseUrl}}/api/pagamentos/1/aprovar
Authorization: Bearer {{token}}
