-- Execute conectado ao database marketplace_desafio.

CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.catalogo_produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    descricao VARCHAR(300) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL CHECK (preco > 0),
    estoque INTEGER NOT NULL CHECK (estoque >= 0),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.carrinhos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ABERTO', 'FINALIZADO', 'CANCELADO')),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrinhos_usuarios
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_carrinhos_produtos
        FOREIGN KEY (produto_id) REFERENCES public.catalogo_produtos (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_carrinhos_usuario_id
    ON public.carrinhos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_carrinhos_produto_id
    ON public.carrinhos (produto_id);

CREATE TABLE IF NOT EXISTS public.confirmacoes_pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrinho_id BIGINT NOT NULL UNIQUE,
    usuario_id BIGINT NOT NULL,
    id_pagamento VARCHAR(80) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDENTE', 'PAGO', 'RECUSADO')),
    valor_pago NUMERIC(12, 2) NOT NULL CHECK (valor_pago > 0),
    confirmado_em TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_pagamentos_carrinhos
        FOREIGN KEY (carrinho_id) REFERENCES public.carrinhos (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_pagamentos_usuarios
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_usuario_id
    ON public.confirmacoes_pagamento (usuario_id);
